01/07/2022 16:23:22 - ERROR    : yaml cfg init err:[Errno 2] No such file or directory: 'config/conf.yaml'
01/07/2022 16:23:32 - ERROR    : yaml cfg init err:[Errno 2] No such file or directory: 'config/conf.yaml'
01/07/2022 16:25:48 - ERROR    : yaml cfg init err:module 'nuitka.build.inline_copy.yaml.yaml' has no attribute 'CLoader'
01/07/2022 16:26:13 - ERROR    : yaml cfg init err:module 'nuitka.build.inline_copy.yaml.yaml' has no attribute 'CLoader'
01/07/2022 17:29:52 - ERROR    : name 'self' is not defined
01/07/2022 17:30:13 - ERROR    : name 'self' is not defined
01/08/2022 12:11:57 - ERROR    : init__error[WinError 10061] 由于目标计算机积极拒绝，无法连接。
01/08/2022 12:13:49 - ERROR    : init__error[WinError 10061] 由于目标计算机积极拒绝，无法连接。
01/08/2022 12:16:21 - ERROR    : init__error[WinError 10061] 由于目标计算机积极拒绝，无法连接。
01/08/2022 16:52:43 - ERROR    : [WinError 10038] 在一个非套接字上尝试了一个操作。
01/08/2022 16:52:48 - ERROR    : [WinError 10038] 在一个非套接字上尝试了一个操作。
01/08/2022 16:52:53 - ERROR    : [WinError 10038] 在一个非套接字上尝试了一个操作。
01/11/2022 08:35:33 - ERROR    : init__errortimed out
01/11/2022 10:16:59 - ERROR    : 'PySide2.QtMultimedia.QMediaPlayer' object has no attribute 'setAudioOutput'
01/11/2022 10:17:00 - ERROR    : init__error'StartApp' object has no attribute 'server'
01/11/2022 10:18:14 - ERROR    : 'PySide2.QtMultimedia.QMediaPlayer' object has no attribute 'setAudioOutput'
01/11/2022 10:18:14 - ERROR    : init__error'StartApp' object has no attribute 'server'
01/11/2022 10:18:20 - ERROR    : 'PySide2.QtMultimedia.QMediaPlayer' object has no attribute 'setAudioOutput'
01/11/2022 10:18:21 - ERROR    : init__error'StartApp' object has no attribute 'server'
01/11/2022 10:19:27 - ERROR    : init__errortimed out
01/11/2022 10:20:19 - ERROR    : init__errortimed out
01/11/2022 10:20:23 - ERROR    : timed out
01/11/2022 10:37:11 - ERROR    : init__errortimed out
01/11/2022 10:38:24 - ERROR    : init__errortimed out
01/11/2022 10:43:40 - ERROR    : init__errortimed out
01/11/2022 10:44:24 - ERROR    : timed out
01/14/2022 11:07:45 - ERROR    : init__errortimed out
01/14/2022 11:09:03 - ERROR    : init__errortimed out
01/14/2022 11:30:20 - ERROR    : 'ellipsis' object has no attribute 'settimeout'
01/14/2022 11:35:06 - ERROR    : init__errortimed out
01/14/2022 11:36:49 - ERROR    : init__errortimed out
01/14/2022 14:15:39 - ERROR    : 'ellipsis' object has no attribute 'settimeout'
01/14/2022 14:16:05 - ERROR    : 'ellipsis' object has no attribute 'settimeout'
01/14/2022 15:11:57 - ERROR    : init__errortimed out
